# This Docker Compose file sets up a local PostgreSQL database for development.

services:
  db:
    # Use the official Postgres 16 image from Docker Hub
    image: postgres:16

    # Environment variables to configure the database
    environment:
      POSTGRES_USER: dev         # username for the database
      POSTGRES_PASSWORD: dev     # password for the database
      POSTGRES_DB: devarena      # database name that will be created automatically

    # Map the database port inside the container (5432) to your local machine’s port (5432)
    ports:
      - "5432:5432"

    # Persist database data between restarts using a named volume
    volumes:
      - pgdata:/var/lib/postgresql/data

# Declare the volume so Docker knows to create and store it outside the container
volumes:
  pgdata:

